Algoritmo "FazSomaProcedimento"
// Descrição Prática 02: Algoritmo para somar dois valores usando procedimentos.
// Data atual  : 09/04/2026
Var
   X,Y: Inteiro

Procedimento Soma( A, B: Inteiro)
Inicio
      Escreval("Recebi o valor ",A)
      Escreval("Recebi o valor ",B)
      Escreval("A soma entre os dois é: ", A+B)
FimProcedimento
Inicio
      X <- 5
      Y <- 3
      Soma(X,Y)  // X e Y iram receber o valor de A e B
Fimalgoritmo